### ISSUE TITLE
Write protect error when usb not plugged in

### ISSUE THREAD

**Issue by lnxsrt** [rabbitholecomputing/ZuluSCSI-V6-firmware#2]
I'm getting `Write protect error writing drive C` on boot to DOS 6.22 with the new ZuluSCSI v6.4 (FW 1.0.2). I can read all files just fine, and scandisk passes with no issue, but no ability to write. 

However, I can read/write from DOS 6.22 without issue when I boot with the USB-C connected to another computer.

**Comment by aperezbios** [comment]
@lnxsrt please contact support@zuluscsi.com with your order number. I don't believe this is a firmware issue.
